<a href="https://colab.research.google.com/github/pankaj09318/Concepts-and-technologies-of-AI/blob/main/Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [7]:
import numpy as np

empty_array = np.empty((2,2))
one_array = np.ones((4,2))

same_array = np.full((2,3),3)
print(same_array)

zero_array = np.zeros_like((one_array))
print(zero_array)

ones = np.ones_like((empty_array))
print(ones)

new_list = [1,2,3,4]
new_list = np.array(new_list)

[[3 3 3]
 [3 3 3]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [31]:
import numpy as np

array1 = np.arange(10,50)
print(array1)

array2 =np.arange(0,9).reshape(3,3)
print(array2)

print(np.eye(3,3))

array3 = np.random.random(30)
mean = array3.mean()
print(array3)
print(mean)

array4 = np.random.random(100).reshape(10,10)
print(array4)
minimum = array4.min()
maximum = array4.max()
print(minimum,maximum)


array5 = np.arange(10)
array5 = np.zeros_like(array5)
array5[4] = 1
print(array5)

array6 = [1,2,0,0,4,0]
array6 = np.array(array6)
array6 = array6[::-1]
print(array6)


array7 = np.zeros((5,5))
array7[:,-1]=1
array7[:,0]=1
array7[0,:]=1
array7[-1,:]=1
print(array7)


array8 = np.zeros((8,8))
array8[1::2,0::2] = 1
array8[::2,1::2] =1
print(array8)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [53]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print(x+y)
print(v+w)
print(x-y)
print(v-w)
print(3*x)
print(4*y)
print(5*v)
print(7*w)
print(x**2)
print(y**2)
print(v**2)
print(w**2)

print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))

print(np.concatenate((x,y),axis=0))
print(np.column_stack((v,w)))

"""
print(np.concatenate((x,v),axis=0))
it shows value error because the dimensions of the input arraysmust have same dimensions as of this x has 2 dimensions and v has 1 dimension.

""";


[[ 6  8]
 [10 13]]
[20 22]
[[-4 -4]
 [-4 -3]]
[-2 -2]
[[ 3  6]
 [ 9 15]]
[[20 24]
 [28 32]]
[45 50]
[77 84]
[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [76]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A1 = np.linalg.inv(A)
print(np.round(np.matmul(A,A1)))
"""
 AA' = [[1 0]   so AA' = I proved
         [0 1]]
"""
print(np.matmul(A,B))
print(np.matmul(B,A))

"""
As AB = [[23 13]  and BA =[[36 44]  so AB != BA proved
         [51 29]]          [13 16]]
"""

print((np.matmul(A,B)).T)
A_T = A.T
B_T = B.T
print(np.matmul(B_T,A_T))

"""
here (AB)T = (BT)(AT) = [[23 51]     so (AB)T = (BT)(AT) proved
                         [13 29]]
"""


"""
2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

"""

A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])
B = np.array([-1,-3,9])

print(np.dot(np.linalg.inv(A),B))


[ 2.  1. -2.]
